# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('artist_name', models.CharField(max_length=200)),
                ('creation_date', models.DateField()),
                ('date_description', models.TextField(blank=True)),
                ('artwork_type', models.TextField()),
                ('medium', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('street_1', models.CharField(blank=True, max_length=200)),
                ('street_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('date_entered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
