# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='artwork_images/')),
                ('author', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('license', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('C', 'Chipping or cracking'), ('D', 'Dirt, dust, bird droppings, or spiderwebs'), ('G', 'Graffiti or vandalism'), ('R', 'Corrosion')], max_length=200)),
                ('damaged', models.BooleanField()),
                ('damaged_description', models.TextField(blank=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checkin_images/')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.Checkin')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
