# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20170618_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
