# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20170621_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_entered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
