# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20170627_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkimage',
            name='author',
        ),
    ]
