# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_auto_20170717_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
