# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20170802_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='damaged',
        ),
        migrations.AddField(
            model_name='checkin',
            name='damage',
            field=models.CharField(blank=True, choices=[('C', 'Chipping or cracking'), ('D', 'Dirt, dust, bird droppings, or spiderwebs'), ('G', 'Graffiti or vandalism'), ('R', 'Corrosion')], max_length=200),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='condition',
            field=models.CharField(choices=[('G', 'Good Condition'), ('D', 'Damaged')], max_length=100),
        ),
    ]
