# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_auto_20170802_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='damage',
        ),
        migrations.AddField(
            model_name='checkin',
            name='damage',
            field=models.ManyToManyField(to='artworks.CheckinDamage'),
        ),
    ]
