# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_auto_20170803_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name': 'Check In'},
        ),
        migrations.AlterModelOptions(
            name='checkindamage',
            options={'verbose_name': 'Check In Damage Descriptions'},
        ),
    ]
