# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_auto_20170807_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkmedium',
            options={'verbose_name': 'Artwork Medium'},
        ),
        migrations.AlterModelOptions(
            name='artworktype',
            options={'verbose_name': 'Artwork Type'},
        ),
    ]
