# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_auto_20170807_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworktype',
            old_name='type',
            new_name='artwork_type',
        ),
    ]
