# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_auto_20170807_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkmedium',
            options={'verbose_name': 'Artwork Medium', 'verbose_name_plural': 'Artwork Medium'},
        ),
        migrations.AlterModelOptions(
            name='artworktype',
            options={'ordering': ['artwork_type'], 'verbose_name': 'Artwork Type', 'verbose_name_plural': 'Artwork Type'},
        ),
    ]
