# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0019_auto_20170829_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_row_header', models.CharField(blank=True, max_length=200)),
                ('first_row_text', models.TextField(blank=True)),
                ('second_row_header', models.CharField(blank=True, max_length=200)),
                ('second_row_column_one_header', models.CharField(blank=True, max_length=200)),
                ('second_row_column_one_text', models.TextField(blank=True)),
                ('second_row_column_two_header', models.CharField(blank=True, max_length=200)),
                ('second_row_column_two_text', models.TextField(blank=True)),
                ('second_row_column_three_header', models.CharField(blank=True, max_length=200)),
                ('second_row_column_three_text', models.TextField(blank=True)),
                ('call_to_action_text', models.TextField(blank=True)),
                ('call_to_action_button', models.CharField(blank=True, max_length=200)),
                ('call_to_action_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
