# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0020_aboutpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'About Page'},
        ),
        migrations.AlterModelOptions(
            name='checkinimage',
            options={'verbose_name': 'Check In Photos'},
        ),
        migrations.AddField(
            model_name='checkinimage',
            name='status',
            field=models.CharField(blank=True, choices=[('H', 'High Priority'), ('L', 'Low Priority'), ('A', 'Archived'), ('R', 'Reviewed')], max_length=100),
        ),
    ]
