# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0021_auto_20171030_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinimage',
            options={'verbose_name_plural': 'Check In Photos'},
        ),
        migrations.AddField(
            model_name='checkinimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
