# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0022_auto_20171030_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='damage',
            field=models.ManyToManyField(blank=True, to='artworks.CheckinDamage'),
        ),
    ]
